# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJqSXqH6noxlYstULlkoQqPXW7zf969G
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="APgpd9Z4OiZUWEK33XfJ")
project = rf.workspace("eye-detection-ghslj").project("diabetic-bddrb")
version = project.version(1)
dataset = version.download("clip")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 10

TRAIN_DIR = "/content/DIABETIC-1/train"
VALID_DIR = "/content/DIABETIC-1/valid"

#Data Generators
train_gen = ImageDataGenerator(rescale=1./255)
val_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_data = val_gen.flow_from_directory(
    VALID_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

#Number of classes
num_classes = len(train_data.class_indices)

#Model
model = Sequential([
    Input(shape=(224, 224, 3)),
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

#Train the model
model.fit(train_data, validation_data=val_data, epochs=EPOCHS)

#Save as .h5
model.save("your_model_name.h5")
print("✅ your_model_name.h5 saved!")